### ISSUE TITLE
Detoxify Roadmap

### ISSUE THREAD

**Issue by laurahanu** [unitaryai/detoxify#26]
Issue to keep track of improvements we'd like to make (in no particular order). Feedback and suggestions welcome!

- [ ] train the `unbiased` model on the Wikipedia dataset from the first challenge as well
- [ ] add a `multilingual` light model (#17)
- [ ] train the `multilingual` model with more languages 
- [ ] add more datasets to training
- [ ] add new categories like personal attack (potentially using https://github.com/ewulczyn/wiki-detox)
- [ ] improve bias metrics & test on different benchmark like [HateCheck](https://arxiv.org/abs/2012.15606)

**Comment by erjonhub** [comment]
Hello, 
What are the languages planned to be added in the roadmap? Is German one of them? Any target date? 

Thank you
